#cloud-config
package_update: true
packages:
  - nginx
  - openssh-server

runcmd:
  - systemctl enable ssh
  - systemctl start ssh
  - echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
  - echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
  - systemctl restart ssh
  - echo "<h1>It works!</h1>" > /var/www/html/index.html