#cloud-config
package_update: true
packages:
  - mysql-server
runcmd:
  - mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'MyDBpass123';"
  - mysql -e "CREATE USER 'webuser'@'%' IDENTIFIED BY 'WebPass123';"
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'webuser'@'%' WITH GRANT OPTION;"
  - sed -i 's/bind-address.*/bind-address = 0.0.0.0/' /etc/mysql/mysql.conf.d/mysqld.cnf
  - systemctl restart mysql