name: Terraform CI/CD

on:
  push:
    branches:
      - main   # Kjør når endringer pushes til main (evt. endre navn til riktig branch)
  pull_request:
    branches:
      - main   # Kjør plan (uten apply) på PR for kodegjennomgang

jobs:
  terraform:
    name: "Terraform Plan & Apply"
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      # Disse secrets må settes opp i GitHub repoet (se forklaring under)

    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v3

      - name: Installer Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -backend-config="resource_group_name=${{ secrets.STATE_RG }}" \
                             -backend-config="storage_account_name=${{ secrets.STATE_STORAGE_ACCOUNT }}" \
                             -backend-config="container_name=${{ secrets.STATE_CONTAINER }}" \
                             -backend-config="key=terraform.tfstate"

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve